//Messenger and chat API constants
export const followApiRoute = '/follow';
export const peopleApiRoute = '/user';
export const chatAPIRoute = '/chat';
export const messengerAPIRoute = '/message';
export const getUserAllChats = `${chatAPIRoute}/getUserChats`;
export const followingUserListAPIUrl = `${followApiRoute}/getFollowingsList`;
export const fetchChatInfo = `${chatAPIRoute}/find`;
export const getUserBySearchAPIUrl = `${peopleApiRoute}/getUserBySearch`;